/*
 * A Reward Library é um projeto real documentado pelos arquivos enviados.
 * Os demais itens fictícios continuam disponíveis apenas para os outros cursos enquanto os projetos reais não chegam.
 */
window.CEUNSP_MOCK_PROJECTS = [
  {
    id: "reward-library",
    title: "Reward Library",
    short_description: "Plataforma digital que aproxima pessoas, bibliotecas e livros, reunindo serviços de biblioteca e elementos de gamificação para incentivar a leitura.",
    description: "Reward Library é uma aplicação web proposta para conectar usuários e bibliotecas, reunindo em uma única plataforma a consulta de livros, o acompanhamento de empréstimos, a divulgação de eventos e o gerenciamento de informações do acervo. A experiência também prevê pontos, ranking e possíveis recompensas como elementos de gamificação para ampliar a participação e incentivar o hábito de leitura.",
    course: "Análise e Desenvolvimento de Sistemas",
    course_acronym: "ADS",
    course_label: "ADS",
    subject: "Análise e Projeto de Sistemas II",
    class_name: "",
    students: ["Omar Rossel", "Rafael Lucas", "Gabriel Nicoletti", "Luan Araujo", "Eduardo Tibo", "Felipe Fernades"],
    technologies: ["HTML", "CSS", "JavaScript", "Node.js", "MySQL", "Git + GitHub"],
    features: ["Consulta de livros", "Empréstimos", "Gestão do acervo", "Eventos e atividades", "Sistema de pontos", "Ranking", "Gamificação para incentivar a leitura"],
    card_technology_limit: 5,
    cover_image: "assets/images/projects/reward-library/reward-library-logo.jpeg",
    cover_fit: "contain",
    project_images: [],
    project_url: "https://qblack7.github.io/RewardsLibrary/",
    link_label: "Acessar projeto",
    github_url: "",
    accent: "#4b1fb8",
    is_mock: false
  },
  {
    id: "mock-03",
    title: "Pulso Urbano",
    short_description: "Painel conceitual para visualizar indicadores e transformar dados em decisões mais claras.",
    description: "Pulso Urbano é um painel demonstrativo que reúne indicadores fictícios em gráficos e resumos objetivos, permitindo explorar diferentes recortes e observar tendências.",
    course: "CURSO EXEMPLO 02",
    filter_course: "Ciência da Computação",
    subject: "DISCIPLINA EXEMPLO 01",
    class_name: "TURMA EXEMPLO B",
    students: ["Aluno Exemplo 06", "Aluno Exemplo 07"],
    technologies: ["Dados", "Dashboards", "JavaScript"],
    cover_image: "assets/images/ceunsp-logo.png",
    project_images: [],
    project_url: "",
    github_url: "",
    accent: "#f31946",
    is_mock: true
  },
  {
    id: "mock-04",
    title: "Conecta Campus",
    short_description: "Protótipo de agenda colaborativa para aproximar estudantes de atividades acadêmicas.",
    description: "Conecta Campus demonstra uma agenda digital de eventos, oficinas e apresentações, com filtros simples e uma visão organizada das atividades disponíveis.",
    course: "CURSO EXEMPLO 02",
    filter_course: "Ciência da Computação",
    subject: "DISCIPLINA EXEMPLO 03",
    class_name: "TURMA EXEMPLO B",
    students: ["Aluno Exemplo 08", "Aluno Exemplo 09"],
    technologies: ["HTML", "CSS", "APIs"],
    cover_image: "assets/images/ceunsp-logo.png",
    project_images: [],
    project_url: "",
    github_url: "",
    accent: "#c02658",
    is_mock: true
  },
  {
    id: "mock-05",
    title: "Atlas Verde",
    short_description: "Catálogo interativo conceitual para registrar iniciativas sustentáveis e seus impactos.",
    description: "Atlas Verde é uma proposta fictícia de catálogo para mapear ações sustentáveis, documentar resultados e tornar informações ambientais mais fáceis de consultar.",
    course: "CURSO EXEMPLO 03",
    filter_course: "Engenharia de Software",
    subject: "DISCIPLINA EXEMPLO 02",
    class_name: "TURMA EXEMPLO C",
    students: ["Aluno Exemplo 10", "Aluno Exemplo 11", "Aluno Exemplo 12"],
    technologies: ["Mapas", "Design", "JavaScript"],
    cover_image: "assets/images/ceunsp-logo.png",
    project_images: [],
    project_url: "",
    github_url: "",
    accent: "#16a085",
    is_mock: true
  },
  {
    id: "mock-06",
    title: "Nexo",
    short_description: "Ambiente demonstrativo para reunir referências, tarefas e registros de equipes acadêmicas.",
    description: "Nexo apresenta uma organização modular para projetos em grupo, reunindo referências, tarefas e registros em um único ambiente conceitual.",
    course: "CURSO EXEMPLO 03",
    filter_course: "Engenharia de Software",
    subject: "DISCIPLINA EXEMPLO 03",
    class_name: "TURMA EXEMPLO C",
    students: ["Aluno Exemplo 13", "Aluno Exemplo 14"],
    technologies: ["UX", "Prototipação", "Pesquisa"],
    cover_image: "assets/images/ceunsp-logo.png",
    project_images: [],
    project_url: "",
    github_url: "",
    accent: "#0f7c83",
    is_mock: true
  }
];
